# Generated by Django 4.0.8 on 2026-08-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_summary_es_course_summary_fr_course_title_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
    ]
