# Generated by Django 4.0.8 on 2026-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_strategy',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVAL', 'Approval Required'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_promoted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
