# Generated by Django 4.0.8 on 2026-08-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_choice_es_choice_choice_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='terminated',
            field=models.BooleanField(default=False, verbose_name='Terminated Due to Violation'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='violation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Violation Reason'),
        ),
    ]
